== Migration notes (May 22, 2024 at 3:09:01 PM COT)

=== Additions

* Bonita projects are now Maven projects and rely on the https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven dependency mechanism] to manage their dependencies. Check the documentation for more information about https://www.bonitasoft.com/bos_redirect.php?bos_redirect_id=727&bos_redirect_major_version=9.0&bos_redirect_minor_version=3&bos_redirect_product=bos[Project composition].
* Bonita Admin Application has been added in the project extensions.

=== Updates

* Groovy version has been updated from `2.4.x` to `3.0.x`
* Only Java `11` version is now supported. This might impact your existing project if you were still using Java 8. Some dependencies in your project might be incompatible with the _Java Platform Module System_ introduced in Java 9.
* Upgrade of java archives files into Maven dependencies:
** `bonita-userfilter-initiator-manager-impl-1.0.0-SNAPSHOT.jar` file has been replaced by a remote Maven dependency with the following coordinates: `org.bonitasoft.actorfilter:bonita-actorfilter-initiator-manager:jar:1.0.0`
** `bonita-connector-google-calendar-v3-create-event-impl-1.0.0.jar` file has been replaced by a remote Maven dependency with the following coordinates: `org.bonitasoft.connectors:bonita-connector-google-calendar-v3:jar:1.1.1`
** `bonita-connector-email-1.2.1.jar` file has been replaced by a remote Maven dependency with the following coordinates: `org.bonitasoft.connectors:bonita-connector-email:jar:1.3.0`

* `com.company.model:bdm-client:jar:1.0.0` dependency has been replaced with `${project.groupId}:vacation-management-example-bdm-model:jar:${project.version}`.
* The project layout has been changed in favor of a multi modules maven project. It means that files location inside the project have changed.  It is a technical change and will not impact the design usage in Bonita Studio.New maven modules and their respective `pom.xml` files are *reserved for internal Studio use*.
* Project's Business Data Model is now build in its own maven module. While it does not impact the design usage, it can now be built and deployed independently from a Studio.  The BDM model dependency share the same `version` and `groupId` of the parent project. It is enforced by the format of the Bonita project and must not be changed.
* `app\.gitignore` file has been updated.
* Rest API Extensions and Themes projects have been moved in the project layout to benefit from the Maven multi module approach. It means that files location inside the project have changed.  It is a technical change and will not impact the design usage in Bonita Studio.New maven modules and their respective `pom.xml` files are *reserved for internal Studio use*.
* Project's extensions are now build in their own maven module. While it does not impact the design usage, this internal change allow the usage of a standard Maven build lifecycle.  All extensions share the same `version` and `groupId` of the parent project. It is enforced by the format of the Bonita project and must not be changed.
* Application module build configuration has been updated to support Maven build.
* tahiti application theme has been updated to Bonita default theme.
* tahiti application layout has been updated to Bonita default layout.
* `default_profile.xml` profile xml schema version has been updated.

=== Removals

* `lib` folder and its content has been removed.
* Deprecated provided groovy classes `BonitaUsers`, `BonitaSql`, `BonitaXML` and `BonitaTypes` have been removed.

